site_name: ht-multidomain
repo_url: https://github.com/robdesideri/ht-multidomain
theme: readthedocs
pages:
- Home: index.md
- ht-multidomain Basics:
  - What is ht-multidomain: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Basic Commands:
- Examples:
- Acknowledgements: acknowledgements.md
